# Generated by Django 2.2.5 on 2019-09-30 03:32

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190928_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('content', froala_editor.fields.FroalaField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='forum.Post')),
            ],
        ),
    ]
