# Generated by Django 2.2.5 on 2019-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
